apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../../../../../apps/tf-training/upstream/tf-job-crds/overlays/application
- ../../../../../apps/tf-training/upstream/tf-job-operator/overlays/application

