apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: kubeflow
  namespace: kubeflow
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: distributions/stacks/openshift/application/openshift/openshift-scc
    name: openshift-scc
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: distributions/stacks/openshift/application/istio-1-3-1-stack
    name: istio-stack
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: distributions/stacks/openshift/application/cluster-local-gateway-1-3-1
    name: cluster-local-gateway
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: distributions/stacks/openshift/application/istio
    name: istio
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: contrib/application/v3
    name: application
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: contrib/metacontroller/base
    name: metacontroller
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: distributions/stacks/openshift/application/cert-manager-crds
    name: cert-manager-crds
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: distributions/stacks/openshift/application/cert-manager-kube-system-resources
    name: cert-manager-kube-system-resources
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: distributions/stacks/openshift/application/cert-manager
    name: cert-manager
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: distributions/stacks/openshift/application/jupyter-web-app
    name: jupyter-web-app
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: distributions/stacks/openshift/application/notebook-controller
    name: notebook-controller
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: distributions/stacks/openshift/application/metadata
    name: metadata
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: distributions/stacks/openshift/application/tf-job
    name: tf-job
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: distributions/stacks/openshift/application/pytorch-job
    name: pytorch-job
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: distributions/stacks/openshift/application/katib
    name: katib
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: distributions/stacks/openshift/application/seldon
    name: seldon
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: distributions/stacks/openshift
    name: kubeflow-apps
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: contrib/tektoncd/tektoncd-install/base
    name: tektoncd-install
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: contrib/tektoncd/tektoncd-dashboard/base
    name: tektoncd-dashboard
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: distributions/stacks/openshift/application/kfp-tekton
    name: kfp-tekton
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: common/knative/installs/generic
    name: knative
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: common/kfserving/installs/generic
    name: kfserving
  repos:
  - name: manifests
    uri: https://github.com/Quant-Analysis-of-Real-Systems/manifests/archive/openshift-fix.tar.gz
  version: master
