apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../../../../../common/istio/istio/base

configMapGenerator:
- name: istio-parameters
  behavior: merge
  envs:
  - params.env
configurations:
- params.yaml
