apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../../../../../apps/pytorch-job/upstream/pytorch-job-crds/overlays/application
- ../../../../../apps/pytorch-job/upstream/pytorch-operator/overlays/application

