apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/component: cert-manager
  app.kubernetes.io/name: cert-manager
  kustomize.component: cert-manager
kind: Kustomization
namespace: cert-manager
resources:
- ../../../../../common/cert-manager/cert-manager/base
- ../../../../../common/cert-manager/cert-manager/overlays/application/application.yaml
- ../../../../../common/cert-manager/cert-manager/overlays/self-signed/cluster-issuer.yaml
configurations:
- ../../../../../common/cert-manager/cert-manager/overlays/application/params.yaml
